kind: Service
apiVersion: v1
metadata:
 name: haproxy-metrics
 labels:
   app: haproxy-metrics # should be same as service labels
 namespace: monitoring
spec:
 type: ClusterIP
 ports:
 - port: 9100 # port of the metric exposed in the VM
   targetPort: 9100
   name: metrics # name required
---
kind: Endpoints
apiVersion: v1
metadata:
 name: haproxy-metrics # same as servic e name
 labels:
   app: haproxy-metrics # should be same as service labels
 namespace: monitoring
subsets:
 - addresses:
     - ip: 192.168.10.15 # ip address of the external VM. Can give multiple IPs as this is an array
   ports:
     - port: 9101
       name: metrics  # name required
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: haproxy-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
       app: haproxy-metrics # should be same as service labels
  endpoints:
  - interval: 30s
    port: metrics