apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
       app: prometheus-node-exporter
       chart: prometheus-node-exporter-1.5.2
       heritage: Tiller
       jobLabel: node-exporter
       release: prom-operator
  endpoints:
  - interval: 30s
    port: metrics # name of the port