apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-node-exporter-rules
  namespace: monitoring
spec:
  groups:
  - name: node-exporter-metrics
    rules:
    - alert: NodeExporterDown
      annotations:
        message: 'Node exporter in the cluster has gone down'
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-cputhrottlinghigh
      expr: 'absent(up{job="node-exporter"} == 1)'
      for: 15m
      labels:
        severity: critical
        env: dev